# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kross

# >> macros
# << macros

# >> bcond_with
# << bcond_with

# >> bcond_without
# << bcond_without

Summary:    KDE Frameworks 5 Tier 3 solution for application scripting
Version:    5.2.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kross.yaml
Source101:  kross-rpmlintrc
Requires:   kf5-filesystem
Requires:   kross-core%{_isa} = %{version}-%{release}
Requires:   kross-ui%{?_isa} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5XmlPatterns)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5UiTools)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kcompletion-devel
BuildRequires:  kcoreaddons-devel
BuildRequires:  kdoctools-devel
BuildRequires:  ki18n-devel
BuildRequires:  kiconthemes-devel
BuildRequires:  kio-devel
BuildRequires:  kparts-devel
BuildRequires:  kservice-devel
BuildRequires:  kwidgetsaddons-devel
BuildRequires:  kxmlgui-devel

%description
KDE Frameworks 5 Tier 3 solution for application scripting


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kcompletion-devel
Requires:   kcoreaddons-devel
Requires:   kdoctools-devel
Requires:   ki18n-devel
Requires:   kiconthemes-devel
Requires:   kio-devel
Requires:   kparts-devel
Requires:   kservice-devel
Requires:   kwidgetsaddons-devel
Requires:   kxmlgui-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%package core
Summary:    Non-gui part of the Kross framework
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-filesystem

%description core
Non-gui part of the Kross framework.


%package ui
Summary:    GUI part of the Sonnet framework
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kross-core%{?_isa} = %{version}-%{release}
Requires:   kf5-filesystem

%description ui
GUI part of the Sonnet framework provides low-level spell checking tools.


%package doc
Summary:    Documentation and user manuals for the Kross framework
Group:      Documentation
Requires:   %{name} = %{version}-%{release}
Requires:   kf5-filesystem

%description doc
Documentation and user manuals for the Kross framework


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
%find_lang kross5_qt --with-qt --all-name || :
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_includedir}/kross_version.h
%{_kf5_includedir}/KrossUi
%{_kf5_includedir}/KrossCore
%{_kf5_libdir}/libKF5KrossCore.so
%{_kf5_libdir}/libKF5KrossUi.so
%{_kf5_cmakedir}/KF5Kross
%{_kf5_mkspecsdir}/qt_*.pri
# >> files devel
# << files devel

%files core -f kross5_qt.lang
%defattr(-,root,root,-)
%{_kf5_bindir}/kf5kross
%{_kf5_libdir}/libKF5KrossCore.so.*
%{_kf5_plugindir}/*
# >> files core
# << files core

%files ui
%defattr(-,root,root,-)
%{_kf5_libdir}/libKF5KrossUi.so.*
%{_kf5_plugindir}/*
# >> files ui
# << files ui

%files doc
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_mandir}/*
# >> files doc
# << files doc
